name: flutter_blockly_example
description: Demonstrates how to use the flutter_blockly plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blockly_plus:
    path: ../
  path_provider: ^2.1.1
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - assets/
  - packages/flutter_blockly_plus/assets/blockly.min.js
  - packages/flutter_blockly_plus/assets/dart_compressed.js
  - packages/flutter_blockly_plus/assets/lua_compressed.js
  - packages/flutter_blockly_plus/assets/python_compressed.js
  - packages/flutter_blockly_plus/assets/php_compressed.js
  - packages/flutter_blockly_plus/assets/javascript_compressed.js