name: flutter_blockly_plus
description: A fork of the flutter_blockly package with additional features and bug fixes.
repository: https://github.com/mobile-blockly/flutter_blockly
version: 0.0.13

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.5.0
  js: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_blockly_plus
      ios:
        default_package: flutter_blockly_plus
      web:
        default_package: flutter_blockly_plus
  assets:
    - assets/

topics:
  - blockly
  - flutter-blockly
  - flutter-blockly-plus
