name: flutter_blockly
description: A Flutter Blockly visual programming editor.
repository: https://github.com/SerSerch/flutter_blockly
issue_tracker: https://github.com/SerSerch/flutter_blockly/issues
version: 0.0.1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

topics:
  - blockly
  - flutter-blockly