name: flutter_blockly_plus
description: A fork of the flutter_blockly package with additional features and bug fixes.
repository: https://github.com/mobile-blockly/flutter_blockly
version: 2.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.5.0
  js: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_blockly_plus
        pluginClass: FlutterBlocklyPlusPlugin
      ios:
        pluginClass: FlutterBlocklyPlusPlugin
      web:
        pluginClass: flutter_blockly_plus
        fileName: flutter_blockly_plus.dart
  assets:
    - assets/
    - assets/blockly.min.js
    - assets/dart_compressed.js
    - assets/lua_compressed.js
    - assets/python_compressed.js
    - assets/php_compressed.js
    - assets/javascript_compressed.js
    - assets/dart_wrapper.js

topics:
  - blockly
  - flutter-blockly
  - flutter-blockly-plus
